version: 2
workflows:
  version: 2
  integration:
    jobs:
      - builder_tooling_stable
      - yart_binary_stable:
          requires:
            - builder_tooling_stable
      - yart_docker_image_stable
          requires:
            - builder_tooling_stable

jobs:
  builder_tooling_stable:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build image
          command: docker build -t tooling --build-arg toolchain="stable" .circleci
      - run:
          name: Push image
          command: >
            docker tag tooling $DOCKER_USER/yart-builder:stable &&
            docker push $DOCKER_USER/yart-builder:stable

  yart_docker_image_stable:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build image
          command: docker build -t yart .
      - run:
          name: Push image
          command: >
            docker tag yart $DOCKER_USER/yart:stable &&
            docker push $DOCKER_USER/yart:stable

  yart_binary_stable:
    docker:
      - image: $DOCKER_USER/yart-builder:stable
    steps:
      - checkout
      - run:
          name: Version informations
          command: |
            echo "===================="
            rustc --version --verbose;
            echo "===================="
            cargo --version --verbose;
            echo "===================="
            rustfmt --version --verbose;
            echo "===================="
            echo -n "Clippy "; cargo clippy --version --verbose;
            echo "===================="

      - run:
          name: Formatting
          command: |
            cargo fmt;
            cargo clippy;

      - run:
          name: Build - Release
          command: cargo build --release && mv target/release/yart /tmp
      - store_artifacts:
          path: /tmp/yart
          destination: yart

      - run:
          name: Build - Debug
          command: cargo build && mv target/debug/yart /tmp
      - store_artifacts:
          path: /tmp/yart
          destination: yart-debug
